name: CI

on: [push, pull_request]

jobs:
  static:
    runs-on: [ubuntu-latest]

    defaults:
      run:
        working-directory: ./src

    steps:
      - name: clone github repository
        uses: actions/checkout@v3

      - name: install python3.10
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
          architecture: 'x64'

      - name: install pipenv
        run: pip install pipenv

      - name: create venv and install dependencies
        run: pipenv install --categories=test-packages --system --deploy --ignore-pipfile

      - name: run flake8
        run: pipenv run flake8 .

      - name: run black
        run: pipenv run black --check .

      - name: run isort
        run: pipenv run isort --check-only .

      - name: run mypy
        run: pipenv run mypy .
